---
- hosts: zisnella-1
  become: yes
  become_method: su
  gather_facts: no

  tasks:
    - name: Update and Install Neede Software
      block:
        - name: enable epel yum repo
          package:
            name: epel-release
            state: latest

        - name: install ansible nmcli module dependencies
          package:
            name: "{{ item }}"
            state: latest
          with_items:
            - python-gobject 
            - NetworkManager-glib

        - name: firewalld should be installed
          package:
            name: "{{ item }}"
            state: latest
          with_items:
            - firewalld

        - name: Centos Virtualization Host software
          package:
            name: "{{ item }}"
            state: latest
          with_items:
            - "@^Virtualization Host"

        - name: Centos Remote System Management software
          package:
            name: "{{ item }}"
            state: latest
          with_items:
            - "@remote-system-management"

        - name: Optional Virtualization Tools
          package:
            name: "{{ item }}"
            state: latest
          with_items:
            - libguestfs-tools
            - virt-install
            - libguestfs-bash-completion

        - name: Optional Tools
          package:
            name: "{{ item }}"
            state: latest
          with_items:
            - git
 
        - name: upgrade all packages
          package:
            name: '*'
            state: latest
 
    - name: Network and Firewall Configuration
      block:
        - name: set eno1 IPv4 address
          nmcli:
            conn_name: eno1
            type: ethernet
            ip4: 192.168.1.11/24
            gw4: 192.168.1.1
            dns4:
              - 8.8.8.8
              - 8.8.4.4
            state: present

        - name: ansible bug fix for static ip
          replace:
            path: /etc/sysconfig/network-scripts/ifcfg-eno1
            regexp: 'BOOTPROTO=dhcp'
            replace: 'BOOTPROTO=none'
            backup: yes

        - name: selinux allow ssh to listen on tcp port 2200
          seport:
            ports: 2200
            proto: tcp
            setype: ssh_port_t
            state: present
 
        - name: firewalld, enabling network services
          firewalld:
            zone: public
            service: "{{ item }}"
            permanent: true
            immediate: true 
            state: enabled
          with_items:
            - ssh
          notify:
            - reload firewalld
       
        - name: firewalld, enabling specific ports
          firewalld:
            zone: public
            port: "{{ item }}"
            permanent: true
            immediate: true 
            state: enabled
          with_items:
            - "2200/tcp"
          notify:
            - reload firewalld

    - name: Start Virtualization Host Services
      block:
        - name: start libvirt service
          service:
            name: libvirtd
            state: started

        - name: enabling routing in the host
          sysctl:
            name: net.ipv4.ip_forward
            value: 1
            sysctl_set: yes
            state: present
            reload: yes
 
  handlers:
    - name: reload firewalld
      service:
        name: firewalld
        state: reloaded
