apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0006
spec:
  capacity:
    storage: 15i 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /pvs/pv0006
    server: "{{ nfs_server }}"
  persistentVolumeReclaimPolicy: Recycle 
