apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /pvs/pv0004
    server: "{{ nfs_server }}"
  persistentVolumeReclaimPolicy: Recycle 
