apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /pvs/pv0001
    server: "{{ nfs_server }}"
  persistentVolumeReclaimPolicy: Recycle 
