apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /pvs/pv0002
    server: "{{ nfs_server }}"
  persistentVolumeReclaimPolicy: Recycle 
