apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005 
spec:
  capacity:
    storage: 15Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /pvs/pv0005
    server: "{{ nfs_server }}"
  persistentVolumeReclaimPolicy: Recycle 
